# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "bulma" "0.6.0" "^0.6.0" "03nqzszv3dcm9a1q0vqpsj0lwc0p9cza08kjxnvhg0cq35c2vd9x")
  (fetchbower "components-font-awesome" "4.7.0" "^4.7.0" "0qpalagbywaxm7wm1i3njcxq52zqs5sqjsmh5sq43s0p596snaly")
  (fetchbower "leaflet" "1.2.0" "^1.2.0" "0li1w0m85217gijmabi2l3172d03gh833fwbgwyx11w8x4dfmx7w")
  (fetchbower "chart.js" "Chart.js#2.7.1" "Chart.js#^2.7.0" "1iczqjnhihbs91c8pvm57v76251ih3asyg88hr35d02bsdabkxb0")
]; }
