# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "components-font-awesome" "4.7.0" "^4.7.0" "0qpalagbywaxm7wm1i3njcxq52zqs5sqjsmh5sq43s0p596snaly")
  (fetchbower "leaflet" "1.2.0" "^1.2.0" "0li1w0m85217gijmabi2l3172d03gh833fwbgwyx11w8x4dfmx7w")
  (fetchbower "chart.js" "Chart.js#2.7.0" "Chart.js#^2.7.0" "0nn3rimqiql7za17hybcz7vxyxizab02vwbd04w2q769npdnhg12")
]; }
